# Generated by Django 5.0.1 on 2024-02-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filiere',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
