# Generated by Django 5.0 on 2024-01-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stage',
            table='stageapp_stage',
        ),
    ]
